### ISSUE TITLE
.env file configuring tips

### ISSUE THREAD

**Issue by hypernucle** [drazisil/mco-server#213]
Since this server is using a 'inner' SQLite, i'm wonder about what i should enter on .env file (ok about server-ip, but what stuff should be entered for DB_USER, DB_HOST and DB_TABLE?)

Currently i'm stuck on "Your registry is out of date" screen.
https://media.discordapp.net/attachments/599660984826855425/599983404842221569/unknown.png

**Comment by hypernucle** [comment]
Another error with unexisting SQLite data:
![image](https://user-images.githubusercontent.com/11505698/61186558-1ee05d80-a691-11e9-85d7-472bc863e249.png)

**Comment by drazisil** [comment]
Should be able to set to anything, but let me update the .example and test
